image: atlassian/default-image:3

pipelines:
    branches:
      release:
        - step:
            script:
            - git remote add sync git@github.com:xtremepush/magento2-plugin.git
            - git checkout release
            - git pull    
            - git push sync master