image: atlassian/default-image:3

pipelines:
    branches:
      release/github:
        - step:
            script:
            - git remote add sync git@github.com:xtremepush/magento2-plugin.git
            - git checkout release/github
            - git pull
            - git commit -m "upstream release"
            - git push sync release/github:master